# .github/workflows/playwright.yml - GitHub Actions integration for Playwright tests
# Runs the test suite on push/pull_request to main.

name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    # Install WordPress and dependencies (using WP-CLI)
    - name: Setup WordPress
      run: |
        curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        php wp-cli.phar core download --allow-root
        php wp-cli.phar core install --url="http://localhost:8080" --title="Test Site" --admin_user="admin" --admin_password="password" --admin_email="admin@example.com" --allow-root
        # Install and activate the plugin via WP-CLI
        php wp-cli.phar plugin install my-plugin --activate --allow-root
    
    # Start WordPress server
    - name: Start WP Server
      run: |
        mkdir -p wp-content/uploads
        php -S localhost:8080 -t . &
        sleep 10  # Wait for server to start
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    
    - name: Run Playwright tests
      run: npx playwright test
      env:
        CI: true
    
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
